use mydb;
ALTER TABLE colleges AUTO_INCREMENT = 1;
ALTER TABLE courses AUTO_INCREMENT = 1;
ALTER TABLE departments AUTO_INCREMENT = 1;
ALTER TABLE professors AUTO_INCREMENT = 1;

ALTER TABLE student_course AUTO_INCREMENT = 1;
ALTER TABLE students AUTO_INCREMENT = 1;
ALTER TABLE terms AUTO_INCREMENT = 1;
ALTER TABLE year_course AUTO_INCREMENT = 1;
ALTER TABLE years AUTO_INCREMENT = 1;
ALTER TABLE enrollment AUTO_INCREMENT = 1;