-- MySQL Script generated by MySQL Workbench
-- Fri Jan 22 09:20:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storedb
-- -----------------------------------------------------
-- stores all the data for the store which can be added to by the forms we are building. This will allow us to insert financial statements using a form. We should think about using the procedures that the forms use to automate the inserts if we have alot of data to do. But the forms could be used as a pos system to make purchases and sales and rent out products.
DROP SCHEMA IF EXISTS `storedb` ;

-- -----------------------------------------------------
-- Schema storedb
--
-- stores all the data for the store which can be added to by the forms we are building. This will allow us to insert financial statements using a form. We should think about using the procedures that the forms use to automate the inserts if we have alot of data to do. But the forms could be used as a pos system to make purchases and sales and rent out products.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storedb` ;
USE `storedb` ;

-- -----------------------------------------------------
-- Table `storedb`.`common_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`common_lookup` (
  `common_lookup_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `common_lookup_type` CHAR(30) NOT NULL,
  `common_lookup_meaning` CHAR(30) NOT NULL,
  `common_lookup_table` CHAR(30) NULL DEFAULT NULL,
  `common_lookup_column` CHAR(30) NULL DEFAULT NULL,
  `common_lookup_code` CHAR(30) NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`common_lookup_id`),
  CONSTRAINT `common_lookup_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `common_lookup_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 337
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `common_lookup_u1` ON `storedb`.`common_lookup` (`common_lookup_table` ASC, `common_lookup_column` ASC, `common_lookup_type` ASC) VISIBLE;

CREATE INDEX `common_lookup_fk1_idx` ON `storedb`.`common_lookup` (`created_by` ASC) VISIBLE;

CREATE INDEX `common_lookup_fk2_idx` ON `storedb`.`common_lookup` (`last_updated_by` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`system_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`system_user` (
  `system_user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `system_user_name` CHAR(20) NOT NULL,
  `system_user_group_id` INT(10) UNSIGNED NOT NULL,
  `system_user_type` INT(10) UNSIGNED NOT NULL,
  `first_name` CHAR(20) NULL DEFAULT NULL,
  `middle_name` CHAR(20) NULL DEFAULT NULL,
  `last_name` CHAR(20) NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`system_user_id`),
  CONSTRAINT `system_user_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `system_user_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `system_user_fk3`
    FOREIGN KEY (`system_user_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `system_user_fk1_idx` ON `storedb`.`system_user` (`created_by` ASC) VISIBLE;

CREATE INDEX `system_user_fk2_idx` ON `storedb`.`system_user` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `system_user_fk3_idx` ON `storedb`.`system_user` (`system_user_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`account_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`account_list` (
  `account_list_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_number` CHAR(10) NOT NULL,
  `consumed_date` DATE NULL DEFAULT NULL,
  `consumed_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_update_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`account_list_id`),
  CONSTRAINT `account_list_fk1`
    FOREIGN KEY (`consumed_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `account_list_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `account_list_fk3`
    FOREIGN KEY (`last_update_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `account_list_fk1_idx` ON `storedb`.`account_list` (`consumed_by` ASC) VISIBLE;

CREATE INDEX `account_list_fk2_idx` ON `storedb`.`account_list` (`created_by` ASC) VISIBLE;

CREATE INDEX `account_list_fk3_idx` ON `storedb`.`account_list` (`last_update_by` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`organization` (
  `organization_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_name` CHAR(30) NOT NULL,
  `organization_type` INT(10) UNSIGNED NOT NULL,
  `tin` CHAR(30) NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`organization_id`),
  CONSTRAINT `organization_fk1`
    FOREIGN KEY (`organization_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `organization_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `organization_fk3`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `organization_fk4`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `oragnization_fk1` ON `storedb`.`organization` (`organization_type` ASC) VISIBLE;

CREATE INDEX `organization_fk2_idx` ON `storedb`.`organization` (`created_by` ASC) VISIBLE;

CREATE INDEX `organization_fk3_idx` ON `storedb`.`organization` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `organization_fk4_idx` ON `storedb`.`organization` (`active_flag` ASC) VISIBLE;

CREATE INDEX `organization_fk5` ON `storedb`.`organization` (`organization_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`member` (
  `member_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_number` CHAR(10) NOT NULL,
  `credit_card_number` CHAR(19) NOT NULL,
  `credit_card_type` INT(10) UNSIGNED NOT NULL,
  `member_type` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`member_id`),
  CONSTRAINT `member_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `member_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `member_fk3`
    FOREIGN KEY (`credit_card_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `member_fk4`
    FOREIGN KEY (`member_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `member_fk1_idx` ON `storedb`.`member` (`created_by` ASC) VISIBLE;

CREATE INDEX `member_fk2_idx` ON `storedb`.`member` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `member_fk3_idx` ON `storedb`.`member` (`credit_card_type` ASC) VISIBLE;

CREATE INDEX `member_fk4_idx` ON `storedb`.`member` (`member_type` ASC) VISIBLE;

CREATE INDEX `account_number_UNIQUE` ON `storedb`.`member` (`account_number` ASC) VISIBLE;

CREATE INDEX `member_id_UNIQUE` ON `storedb`.`member` (`member_id` ASC) VISIBLE;

CREATE INDEX `credit_card_number_UNIQUE` ON `storedb`.`member` (`credit_card_number` ASC) VISIBLE;

CREATE INDEX `credit_card_type_UNIQUE` ON `storedb`.`member` (`credit_card_type` ASC) VISIBLE;

CREATE INDEX `created_by_UNIQUE` ON `storedb`.`member` (`created_by` ASC) VISIBLE;

CREATE INDEX `creation_date_UNIQUE` ON `storedb`.`member` (`creation_date` ASC) VISIBLE;

CREATE INDEX `last_updated_by_UNIQUE` ON `storedb`.`member` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `last_update_date_UNIQUE` ON `storedb`.`member` (`last_update_date` ASC) VISIBLE;

CREATE INDEX `member_type_UNIQUE` ON `storedb`.`member` (`member_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`job` (
  `job_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` INT(10) UNSIGNED NOT NULL,
  `job_title` CHAR(50) NOT NULL,
  `job_type` INT(10) UNSIGNED NOT NULL,
  `job_description` CHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`job_id`),
  CONSTRAINT `job_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `job_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `job_fk3`
    FOREIGN KEY (`org_id`)
    REFERENCES `storedb`.`organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_fk4`
    FOREIGN KEY (`job_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `job_fk1_idx` ON `storedb`.`job` (`created_by` ASC) VISIBLE;

CREATE INDEX `job_fk2_idx` ON `storedb`.`job` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `job_fk3_idx` ON `storedb`.`job` (`org_id` ASC) VISIBLE;

CREATE INDEX `job_fk4_idx` ON `storedb`.`job` (`job_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`contact` (
  `contact_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  `member_id` INT(10) UNSIGNED NOT NULL,
  `job_id` INT(10) UNSIGNED NULL,
  `org_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `employee_number` CHAR(10) NULL DEFAULT NULL,
  `contact_type` INT(10) UNSIGNED NOT NULL,
  `first_name` CHAR(20) NOT NULL,
  `middle_name` CHAR(20) NULL DEFAULT NULL,
  `last_name` CHAR(20) NOT NULL,
  `gender_type` INT(10) NULL DEFAULT NULL,
  `ssan` CHAR(11) NOT NULL,
  `employee_photo` MEDIUMBLOB NULL,
  `dob` DATE NULL,
  `race_type` INT(10) UNSIGNED NULL,
  `marital_type` INT(10) UNSIGNED NULL,
  `employee_type` INT(10) UNSIGNED NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`contact_id`),
  CONSTRAINT `contact_fk1`
    FOREIGN KEY (`member_id`)
    REFERENCES `storedb`.`member` (`member_id`),
  CONSTRAINT `contact_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `contact_fk3`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `contact_fk4`
    FOREIGN KEY (`organization_id`)
    REFERENCES `storedb`.`organization` (`organization_id`),
  CONSTRAINT `contact_fk5`
    FOREIGN KEY (`contact_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `contact_fk6`
    FOREIGN KEY (`race_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contact_fk7`
    FOREIGN KEY (`marital_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contact_fk8`
    FOREIGN KEY (`job_id`)
    REFERENCES `storedb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contact_fk9`
    FOREIGN KEY (`employee_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `contact_fk1_idx` ON `storedb`.`contact` (`member_id` ASC) VISIBLE;

CREATE INDEX `contact_fk2_idx` ON `storedb`.`contact` (`created_by` ASC) VISIBLE;

CREATE INDEX `contact_fk3_idx` ON `storedb`.`contact` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `contact_fk4_idx` ON `storedb`.`contact` (`organization_id` ASC) VISIBLE;

CREATE INDEX `contact_fk5_idx` ON `storedb`.`contact` (`contact_type` ASC) VISIBLE;

CREATE INDEX `contact_fk6_idx` ON `storedb`.`contact` (`race_type` ASC) VISIBLE;

CREATE INDEX `contact_fk7_idx` ON `storedb`.`contact` (`marital_type` ASC) VISIBLE;

CREATE INDEX `contact_fk8_idx` ON `storedb`.`contact` (`job_id` ASC) VISIBLE;

CREATE INDEX `contact_fk9_idx` ON `storedb`.`contact` (`employee_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`country` (
  `country_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_name` INT(10) UNSIGNED NOT NULL,
  `county_code` CHAR(2) NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `storedb`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`state` (
  `state_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_id` INT(10) UNSIGNED NOT NULL,
  `state_code` CHAR(3) NOT NULL,
  `state_name` CHAR(30) NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`state_id`),
  CONSTRAINT `state_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `state_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `state_fk3`
    FOREIGN KEY (`country_id`)
    REFERENCES `storedb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_airport_1` ON `storedb`.`state` (`created_by` ASC) VISIBLE;

CREATE INDEX `fk_airport_2` ON `storedb`.`state` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `state_fk3_idx` ON `storedb`.`state` (`country_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`county`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`county` (
  `county_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state_id` INT(10) UNSIGNED NOT NULL,
  `county_name` CHAR(30) NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`county_id`),
  CONSTRAINT `fk_airport_100`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `fk_airport_200`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `county_fk1`
    FOREIGN KEY (`state_id`)
    REFERENCES `storedb`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_airport_1` ON `storedb`.`county` (`created_by` ASC) VISIBLE;

CREATE INDEX `fk_airport_2` ON `storedb`.`county` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `county_fk1_idx` ON `storedb`.`county` (`state_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`city` (
  `city_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `county_id` INT(10) UNSIGNED NULL,
  `state_id` INT(10) UNSIGNED NULL,
  `city_name` CHAR(30) NOT NULL,
  `state_province` CHAR(30) NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`city_id`),
  CONSTRAINT `fk_airport_1000`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `fk_airport_2000`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `city_fk1`
    FOREIGN KEY (`county_id`)
    REFERENCES `storedb`.`county` (`county_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `city_fk2`
    FOREIGN KEY (`state_id`)
    REFERENCES `storedb`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_airport_1` ON `storedb`.`city` (`created_by` ASC) VISIBLE;

CREATE INDEX `fk_airport_2` ON `storedb`.`city` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `city_fk1_idx` ON `storedb`.`city` (`county_id` ASC) VISIBLE;

CREATE INDEX `city_fk2_idx` ON `storedb`.`city` (`state_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`address` (
  `address_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `address_type` INT(10) UNSIGNED NOT NULL,
  `city_id` INT(10) UNSIGNED NOT NULL,
  `state_id` INT(10) UNSIGNED NOT NULL,
  `county_id` INT(10) UNSIGNED NULL,
  `postal_code` CHAR(20) NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `address_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `address_fk3`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `address_fk4`
    FOREIGN KEY (`organization_id`)
    REFERENCES `storedb`.`organization` (`organization_id`),
  CONSTRAINT `address_fk5`
    FOREIGN KEY (`contact_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address_fk6`
    FOREIGN KEY (`city_id`)
    REFERENCES `storedb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address_fk7`
    FOREIGN KEY (`county_id`)
    REFERENCES `storedb`.`county` (`county_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address_fk8`
    FOREIGN KEY (`state_id`)
    REFERENCES `storedb`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `address_fk2_idx` ON `storedb`.`address` (`created_by` ASC) VISIBLE;

CREATE INDEX `address_fk3_idx` ON `storedb`.`address` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `address_fk4_idx` ON `storedb`.`address` (`organization_id` ASC) VISIBLE;

CREATE INDEX `address_fk5_idx` ON `storedb`.`address` (`contact_id` ASC) VISIBLE;

CREATE INDEX `address_fk6_idx` ON `storedb`.`address` (`city_id` ASC) VISIBLE;

CREATE INDEX `address_fk7_idx` ON `storedb`.`address` (`county_id` ASC) VISIBLE;

CREATE INDEX `address_fk8_idx` ON `storedb`.`address` (`state_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`airport` (
  `airport_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `airport_code` CHAR(3) NOT NULL,
  `airport_name` CHAR(30) NOT NULL,
  `airport_city_id` INT(10) UNSIGNED NOT NULL,
  `city_id` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`airport_id`),
  CONSTRAINT `fk_airport_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `fk_airport_2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `fk_airport_3`
    FOREIGN KEY (`city_id`)
    REFERENCES `storedb`.`state` (`state_id`),
  CONSTRAINT `fk_airport_4`
    FOREIGN KEY (`airport_city_id`)
    REFERENCES `storedb`.`state` (`state_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_airport_1_idx` ON `storedb`.`airport` (`created_by` ASC) VISIBLE;

CREATE INDEX `fk_airport_2_idx` ON `storedb`.`airport` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `fk_airport_3_idx` ON `storedb`.`airport` (`city_id` ASC) VISIBLE;

CREATE INDEX `fk_airport_4_idx` ON `storedb`.`airport` (`airport_city_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`benefit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`benefit` (
  `benefit_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `employee_contribution` DECIMAL(10,2) NULL DEFAULT NULL,
  `employer_contribution` DECIMAL(10,2) NULL DEFAULT NULL,
  `benefit_type` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`benefit_id`),
  CONSTRAINT `benefit_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `benefit_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `benefit_fk3`
    FOREIGN KEY (`benefit_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `benefit_fk4`
    FOREIGN KEY (`org_id`)
    REFERENCES `storedb`.`organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `benefit_fk1_idx` ON `storedb`.`benefit` (`created_by` ASC) VISIBLE;

CREATE INDEX `benefit_fk2_idx` ON `storedb`.`benefit` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `benefit_fk3_idx` ON `storedb`.`benefit` (`benefit_type` ASC) VISIBLE;

CREATE INDEX `benefit_fk4_idx` ON `storedb`.`benefit` (`org_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`bonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`bonus` (
  `bonus_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `org_id` INT(10) UNSIGNED NOT NULL,
  `bonus_amount` DECIMAL(10,2) NOT NULL,
  `bonus_date` DATE NOT NULL,
  `paid_date` DATE NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`bonus_id`),
  CONSTRAINT `bonus_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `bonus_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `bonus_fk3`
    FOREIGN KEY (`org_id`)
    REFERENCES `storedb`.`organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bonus_fk4`
    FOREIGN KEY (`employee_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `bonus_fk1_idx` ON `storedb`.`bonus` (`created_by` ASC) VISIBLE;

CREATE INDEX `bonus_fk2_idx` ON `storedb`.`bonus` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `bonus_fk3_idx` ON `storedb`.`bonus` (`org_id` ASC) VISIBLE;

CREATE INDEX `bonus_fk4_idx` ON `storedb`.`bonus` (`employee_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`calendar` (
  `calendar_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `calendar_name` CHAR(10) NULL DEFAULT NULL,
  `calendar_short_name` CHAR(3) NULL DEFAULT NULL,
  `period_name` CHAR(30) NULL DEFAULT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`calendar_id`),
  CONSTRAINT `calendar_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `calendar_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `calendar_fk3`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `calendar_fk1_idx` ON `storedb`.`calendar` (`created_by` ASC) VISIBLE;

CREATE INDEX `calendar_fk2_idx` ON `storedb`.`calendar` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `calendar_fk3_idx` ON `storedb`.`calendar` (`active_flag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`chart_of_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`chart_of_account` (
  `account_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_number` CHAR(10) NOT NULL,
  `account_group_type` INT(10) UNSIGNED NOT NULL,
  `ledger_type` INT(10) UNSIGNED NOT NULL,
  `account_type` INT(10) UNSIGNED NOT NULL,
  `account_code` INT(10) UNSIGNED NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_update_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `chart_of_account_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `chart_of_account_fk2`
    FOREIGN KEY (`last_update_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `chart_of_account_fk4`
    FOREIGN KEY (`account_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `chart_of_account_fk5`
    FOREIGN KEY (`account_group_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `chart_of_account_fk6`
    FOREIGN KEY (`ledger_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `chart_of_account_fk1_idx` ON `storedb`.`chart_of_account` (`created_by` ASC) VISIBLE;

CREATE INDEX `chart_of_account_fk2_idx` ON `storedb`.`chart_of_account` (`last_update_by` ASC) VISIBLE;

CREATE INDEX `chart_of_account_fk4_idx` ON `storedb`.`chart_of_account` (`account_type` ASC) VISIBLE;

CREATE INDEX `chart_of_account_fk5_idx` ON `storedb`.`chart_of_account` (`account_group_type` ASC) VISIBLE;

CREATE INDEX `chart_of_account_fk6_idx` ON `storedb`.`chart_of_account` (`ledger_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`item_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`item_rating` (
  `item_rating_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_rating` CHAR(8) NULL DEFAULT NULL,
  `item_rating_meaning` CHAR(40) NULL,
  `item_rating_agency` CHAR(4) NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` INT(10) NOT NULL,
  PRIMARY KEY (`item_rating_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `storedb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`genre` (
  `genre_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `genre` CHAR(50) NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `storedb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`item` (
  `item_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_rating_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `genre_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `item_asin` CHAR(14) NOT NULL,
  `item_type` INT(10) UNSIGNED NULL,
  `item_title` VARCHAR(1000) NOT NULL,
  `item_subtitle` VARCHAR(500) NULL DEFAULT NULL,
  `item_release_date` DATE NOT NULL,
  `item_screen_type` INT(45) UNSIGNED NULL DEFAULT NULL,
  `item_image_url` CHAR(100) NULL DEFAULT NULL,
  `item_case` TINYINT(1) NOT NULL,
  `case_quantity` INT(10) NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `item_fk1`
    FOREIGN KEY (`item_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `item_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `item_fk3`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `item_fk4`
    FOREIGN KEY (`item_rating_id`)
    REFERENCES `storedb`.`item_rating` (`item_rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_fk5`
    FOREIGN KEY (`genre_id`)
    REFERENCES `storedb`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `item_fk1_idx` ON `storedb`.`item` (`item_type` ASC) VISIBLE;

CREATE INDEX `item_fk2_idx` ON `storedb`.`item` (`created_by` ASC) VISIBLE;

CREATE INDEX `item_fk3_idx` ON `storedb`.`item` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `item_fk4_idx` ON `storedb`.`item` (`item_rating_id` ASC) VISIBLE;

CREATE INDEX `item_fk5_idx` ON `storedb`.`item` (`genre_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`purchase_order` (
  `purchase_order_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `purchase_quantity` INT(10) NULL DEFAULT NULL,
  `purchase_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`purchase_order_id`),
  CONSTRAINT `purchase_order_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `purchase_order_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `purchase_order_fk3`
    FOREIGN KEY (`contact_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `purchase_order_fk1_idx` ON `storedb`.`purchase_order` (`created_by` ASC) VISIBLE;

CREATE INDEX `purchase_order_fk2_idx` ON `storedb`.`purchase_order` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `purchase_order_fk3_idx` ON `storedb`.`purchase_order` (`contact_id` ASC) VISIBLE;

CREATE INDEX `purchase_order_id` ON `storedb`.`purchase_order` (`purchase_order_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`discount` (
  `discounts_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT(10) UNSIGNED NULL,
  `purchase_order_id` INT(10) UNSIGNED NULL,
  `discount_percent` DECIMAL(10,2) NOT NULL,
  `discount_amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`discounts_id`),
  CONSTRAINT `discount_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `discount_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `discount_fk3`
    FOREIGN KEY (`item_id`)
    REFERENCES `storedb`.`item` (`item_id`),
  CONSTRAINT `discount_fk4`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `storedb`.`purchase_order` (`purchase_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `discount_fk1_idx` ON `storedb`.`discount` (`created_by` ASC) VISIBLE;

CREATE INDEX `discount_fk2_idx` ON `storedb`.`discount` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `discount_fk3_idx` ON `storedb`.`discount` (`item_id` ASC) VISIBLE;

CREATE INDEX `discount_fk4_idx` ON `storedb`.`discount` (`purchase_order_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`employee_benefit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`employee_benefit` (
  `benefit_id` INT(10) UNSIGNED NOT NULL,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `org_id` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`benefit_id`, `employee_id`, `org_id`),
  CONSTRAINT `employee_benefit_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `employee_benefit_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `employee_benefit_fk3`
    FOREIGN KEY (`org_id`)
    REFERENCES `storedb`.`organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_benefit_fk4`
    FOREIGN KEY (`employee_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_benefit_fk5`
    FOREIGN KEY (`benefit_id`)
    REFERENCES `storedb`.`benefit` (`benefit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `employee_benefit_fk1_idx` ON `storedb`.`employee_benefit` (`created_by` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk2_idx` ON `storedb`.`employee_benefit` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk3_idx` ON `storedb`.`employee_benefit` (`org_id` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk4_idx` ON `storedb`.`employee_benefit` (`employee_id` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk5_idx` ON `storedb`.`employee_benefit` (`benefit_id` ASC) VISIBLE;

CREATE INDEX `employee_benefit_pk1` ON `storedb`.`employee_benefit` (`benefit_id` ASC, `employee_id` ASC, `org_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`employee_bonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`employee_bonus` (
  `bonus_id` INT(10) UNSIGNED NOT NULL,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `org_id` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`bonus_id`, `employee_id`, `org_id`),
  CONSTRAINT `employee_bonus_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `employee_bonus_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `employee_bonus_fk3`
    FOREIGN KEY (`org_id`)
    REFERENCES `storedb`.`organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_bonus_fk4`
    FOREIGN KEY (`employee_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_bonus_fk5`
    FOREIGN KEY (`bonus_id`)
    REFERENCES `storedb`.`bonus` (`bonus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `employee_benefit_fk1` ON `storedb`.`employee_bonus` (`created_by` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk2` ON `storedb`.`employee_bonus` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk3` ON `storedb`.`employee_bonus` (`org_id` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk4` ON `storedb`.`employee_bonus` (`employee_id` ASC) VISIBLE;

CREATE INDEX `employee_benefit_fk5` ON `storedb`.`employee_bonus` (`bonus_id` ASC) VISIBLE;

CREATE INDEX `employee_benefit_pk1` ON `storedb`.`employee_bonus` (`bonus_id` ASC, `employee_id` ASC, `org_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`rental` (
  `rental_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `check_out_date` DATE NOT NULL,
  `expected_return_date` DATE NOT NULL,
  `actual_return_date` DATE NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`rental_id`),
  CONSTRAINT `rental_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `rental_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `rental_fk3`
    FOREIGN KEY (`contact_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `rental_fk1_idx` ON `storedb`.`rental` (`created_by` ASC) VISIBLE;

CREATE INDEX `rental_fk2_idx` ON `storedb`.`rental` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `rental_fk3_idx` ON `storedb`.`rental` (`contact_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`invoice` (
  `invoice_id` INT(10) UNSIGNED AUTO_INCREMENT,
  `invoice_num` INT(10) UNSIGNED,
  `rental_id` INT(10) UNSIGNED NOT NULL,
  `invoice_price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `invoice_date` DATE NOT NULL,
  `invoice_pay_flag` INT(10) UNSIGNED NOT NULL,
  `request_quantity` INT(10) UNSIGNED NOT NULL,
  `purchase_price` DECIMAL(10,2) NOT NULL,
  `purchase_date` DATE NOT NULL,
  `purchase_method_type` INT(10) UNSIGNED NOT NULL,
  `invoice_type` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_update_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`invoice_id`, `invoice_num`),
  CONSTRAINT `invoice_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `invoice_fk2`
    FOREIGN KEY (`last_update_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `invoice_fk3`
    FOREIGN KEY (`rental_id`)
    REFERENCES `storedb`.`rental` (`rental_id`),
  CONSTRAINT `invoice_fk4`
    FOREIGN KEY (`purchase_method_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `invoice_fk5`
    FOREIGN KEY (`invoice_pay_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `invoice_fk6`
    FOREIGN KEY (`invoice_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `invoice_fk1_idx` ON `storedb`.`invoice` (`created_by` ASC) VISIBLE;

CREATE INDEX `invoice_fk2_idx` ON `storedb`.`invoice` (`last_update_by` ASC) VISIBLE;

CREATE INDEX `invoice_fk3_idx` ON `storedb`.`invoice` (`rental_id` ASC) VISIBLE;

CREATE INDEX `invoice_fk4_idx` ON `storedb`.`invoice` (`purchase_method_type` ASC) VISIBLE;

CREATE INDEX `invoice_fk5_idx` ON `storedb`.`invoice` (`invoice_pay_flag` ASC) VISIBLE;

CREATE INDEX `invoice_fk6_idx` ON `storedb`.`invoice` (`invoice_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`state_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`state_tax` (
  `state_tax_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state_id` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`state_tax_id`),
  CONSTRAINT `state_tax_fk1`
    FOREIGN KEY (`state_id`)
    REFERENCES `storedb`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `state_tax_fk2`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `state_tax_fk1_idx` ON `storedb`.`state_tax` (`state_id` ASC) VISIBLE;

CREATE INDEX `state_tax_fk2_idx` ON `storedb`.`state_tax` (`active_flag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`county_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`county_tax` (
  `county_tax_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `county_id` INT(10) UNSIGNED NOT NULL,
  `state_tax_id` INT(10) UNSIGNED NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`county_tax_id`),
  CONSTRAINT `county_tax_fk1`
    FOREIGN KEY (`county_id`)
    REFERENCES `storedb`.`county` (`county_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `county_tax_fk2`
    FOREIGN KEY (`state_tax_id`)
    REFERENCES `storedb`.`state_tax` (`state_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `county_tax_fk3`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `county_tax_fk1_idx` ON `storedb`.`county_tax` (`county_id` ASC) VISIBLE;

CREATE INDEX `county_tax_fk2_idx` ON `storedb`.`county_tax` (`state_tax_id` ASC) VISIBLE;

CREATE INDEX `county_tax_fk3_idx` ON `storedb`.`county_tax` (`active_flag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`city_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`city_tax` (
  `city_tax_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `county_tax_id` INT(10) UNSIGNED NOT NULL,
  `state_tax_id` INT(10) UNSIGNED NOT NULL,
  `city_id` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`city_tax_id`),
  CONSTRAINT `city_tax_fk1`
    FOREIGN KEY (`state_tax_id`)
    REFERENCES `storedb`.`state_tax` (`state_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `city_tax_fk2`
    FOREIGN KEY (`county_tax_id`)
    REFERENCES `storedb`.`county_tax` (`county_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `city_tax_fk3`
    FOREIGN KEY (`city_id`)
    REFERENCES `storedb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `city_tax_fk4`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `city_tax_fk1_idx` ON `storedb`.`city_tax` (`state_tax_id` ASC) VISIBLE;

CREATE INDEX `city_tax_fk2_idx` ON `storedb`.`city_tax` (`county_tax_id` ASC) VISIBLE;

CREATE INDEX `city_tax_fk3_idx` ON `storedb`.`city_tax` (`city_id` ASC) VISIBLE;

CREATE INDEX `city_tax_fk4_idx` ON `storedb`.`city_tax` (`active_flag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`sales_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`sales_tax` (
  `sales_tax_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `county_tax_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `city_tax_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `state_tax_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `sales_tax_percent` DECIMAL(10,2) NOT NULL,
  `effective_start_date` DATE NOT NULL,
  `effective_end_date` DATE NOT NULL,
  `sales_tax_type` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`sales_tax_id`),
  CONSTRAINT `sales_tax_fk1`
    FOREIGN KEY (`city_tax_id`)
    REFERENCES `storedb`.`city_tax` (`city_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_tax_fk2`
    FOREIGN KEY (`county_tax_id`)
    REFERENCES `storedb`.`county_tax` (`county_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_tax_fk3`
    FOREIGN KEY (`state_tax_id`)
    REFERENCES `storedb`.`state_tax` (`state_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `sales_tax_fk1_idx` ON `storedb`.`sales_tax` (`city_tax_id` ASC) VISIBLE;

CREATE INDEX `sales_tax_fk2_idx` ON `storedb`.`sales_tax` (`county_tax_id` ASC) VISIBLE;

CREATE INDEX `sales_tax_fk3_idx` ON `storedb`.`sales_tax` (`state_tax_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`vat_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`vat_tax` (
  `vat_tax_id` INT(10) UNSIGNED NOT NULL,
  `country_id` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `active_flag` INT(10) NOT NULL,
  `percentage_amount` DOUBLE UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_update_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`vat_tax_id`),
  CONSTRAINT `vat_tax_fk1`
    FOREIGN KEY (`country_id`)
    REFERENCES `storedb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `vat_tax_fk1_idx` ON `storedb`.`vat_tax` (`country_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`general_ledger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`general_ledger` (
  `coa_id` INT(10) UNSIGNED,
  `invoice_id` INT(10) UNSIGNED,
  `sales_tax_id` INT(10) UNSIGNED,
  `purchase_order_id` INT(10) UNSIGNED,
  `vat_tax_id` INT(10) UNSIGNED NULL,
  `calendar_id` INT(10) UNSIGNED NULL,
  `transaction_amount` DECIMAL(10,2) NOT NULL,
  `transaction_date` DATE NULL DEFAULT NULL,
  `payment_method_type` INT(10) UNSIGNED NOT NULL,
  `transaction_type` INT(10) UNSIGNED NOT NULL,
  `transaction_account` CHAR(15) NULL DEFAULT NULL,
  `payment_account_number` CHAR(19) NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`coa_id`, `invoice_id`, `sales_tax_id`, `purchase_order_id`),
  CONSTRAINT `general_ledger_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `general_ledger_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `general_ledger_fk3`
    FOREIGN KEY (`coa_id`)
    REFERENCES `storedb`.`chart_of_account` (`account_id`),
  CONSTRAINT `general_ledger_fk4`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `storedb`.`invoice` (`invoice_id`),
  CONSTRAINT `general_ledger_fk5`
    FOREIGN KEY (`payment_method_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `general_ledger_fk6`
    FOREIGN KEY (`transaction_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `general_ledger_fk8`
    FOREIGN KEY (`sales_tax_id`)
    REFERENCES `storedb`.`sales_tax` (`sales_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `general_ledger_fk9`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `storedb`.`purchase_order` (`purchase_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `general_ledger_fk10`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `storedb`.`calendar` (`calendar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `general_ledger_fk11`
    FOREIGN KEY (`vat_tax_id`)
    REFERENCES `storedb`.`vat_tax` (`vat_tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `general_ledger_fk1_idx` ON `storedb`.`general_ledger` (`created_by` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk2_idx` ON `storedb`.`general_ledger` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk3_idx` ON `storedb`.`general_ledger` (`coa_id` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk4_idx` ON `storedb`.`general_ledger` (`invoice_id` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk5_idx` ON `storedb`.`general_ledger` (`payment_method_type` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk6_idx` ON `storedb`.`general_ledger` (`transaction_type` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk8_idx` ON `storedb`.`general_ledger` (`sales_tax_id` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk9_idx` ON `storedb`.`general_ledger` (`purchase_order_id` ASC) VISIBLE;

CREATE INDEX `general_ledger_pk1` ON `storedb`.`general_ledger` (`coa_id` ASC, `invoice_id` ASC, `sales_tax_id` ASC, `purchase_order_id` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk10_idx` ON `storedb`.`general_ledger` (`calendar_id` ASC) VISIBLE;

CREATE INDEX `general_ledger_fk11_idx` ON `storedb`.`general_ledger` (`vat_tax_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`inventory_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`inventory_organization` (
  `organization_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_name` CHAR(20) NOT NULL,
  `organization_type` INT(10) UNSIGNED NOT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`organization_id`),
  CONSTRAINT `inventory_organization_fk1`
    FOREIGN KEY (`organization_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `inventory_organization_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `inventory_organization_fk3`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `inventory_organization_fk4`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `inventory_organization_fk1_idx` ON `storedb`.`inventory_organization` (`organization_type` ASC) VISIBLE;

CREATE INDEX `inventory_organization_fk2_idx` ON `storedb`.`inventory_organization` (`created_by` ASC) VISIBLE;

CREATE INDEX `inventory_organization_fk3_idx` ON `storedb`.`inventory_organization` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `inventory_organization_fk4_idx` ON `storedb`.`inventory_organization` (`active_flag` ASC) VISIBLE;

CREATE INDEX `inventory_organization_fk5` ON `storedb`.`inventory_organization` (`organization_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`inventory` (
  `inventory_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT(10) UNSIGNED NOT NULL,
  `org_id` INT(10) UNSIGNED NULL,
  `in_stock_date` DATE NULL DEFAULT NULL,
  `out_stock_date` DATE NULL DEFAULT NULL,
  `consumed_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  `consumed_date` DATE NULL DEFAULT NULL,
  `inventory_item_type` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`inventory_id`),
  CONSTRAINT `inventory_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `inventory_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `inventory_fk3`
    FOREIGN KEY (`item_id`)
    REFERENCES `storedb`.`item` (`item_id`),
  CONSTRAINT `inventory_fk5`
    FOREIGN KEY (`org_id`)
    REFERENCES `storedb`.`inventory_organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `inventory_fk1_idx` ON `storedb`.`inventory` (`created_by` ASC) VISIBLE;

CREATE INDEX `inventory_fk2_idx` ON `storedb`.`inventory` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `inventory_fk3_idx` ON `storedb`.`inventory` (`item_id` ASC) VISIBLE;

CREATE INDEX `inventory_fk5_idx` ON `storedb`.`inventory` (`org_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`inventory_organization_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`inventory_organization_structure` (
  `org_structure_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  `org_structure_parent_id` INT(10) UNSIGNED NOT NULL,
  `org_structure_child_id` INT(10) UNSIGNED NOT NULL,
  `org_structure_type` INT(10) UNSIGNED NOT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`org_structure_id`),
  CONSTRAINT `inventory_organization_structure_fk1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `storedb`.`inventory_organization` (`organization_id`),
  CONSTRAINT `inventory_organization_structure_fk2`
    FOREIGN KEY (`org_structure_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `inventory_organization_structure_fk3`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `inventory_organization_structure_fk4`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `inventory_organization_structure_fk5`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `inventory_organization_structure_fk1_idx` ON `storedb`.`inventory_organization_structure` (`organization_id` ASC) VISIBLE;

CREATE INDEX `inventory_organization_structure_fk2_idx` ON `storedb`.`inventory_organization_structure` (`org_structure_type` ASC) VISIBLE;

CREATE INDEX `inventory_organization_structure_fk3_idx` ON `storedb`.`inventory_organization_structure` (`created_by` ASC) VISIBLE;

CREATE INDEX `inventory_organization_structure_fk4_idx` ON `storedb`.`inventory_organization_structure` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `inventory_organization_structure_fk5_idx` ON `storedb`.`inventory_organization_structure` (`active_flag` ASC) VISIBLE;

CREATE INDEX `inventory_organization_structure_fk6` ON `storedb`.`inventory_organization_structure` (`org_structure_child_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`invoice_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`invoice_item` (
  `invoice_id` INT(10) UNSIGNED,
  `item_id` INT(10) UNSIGNED NOT NULL,
  `inventory_id` INT(10) UNSIGNED NOT NULL,
  `invoice_item_amount` DECIMAL(10,2) NOT NULL,
  `created_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  `creation_date` DATE NULL DEFAULT NULL,
  `last_updated_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  `last_update_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`, `invoice_id`, `inventory_id`),
  CONSTRAINT `invoice_item_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `invoice_item_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `invoice_item_fk3`
    FOREIGN KEY (`item_id`)
    REFERENCES `storedb`.`item` (`item_id`),
  CONSTRAINT `invoice_item_fk4`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `storedb`.`invoice` (`invoice_id`),
  CONSTRAINT `invoice_item_fk5`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `storedb`.`inventory` (`inventory_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `invoice_item_fk1_idx` ON `storedb`.`invoice_item` (`created_by` ASC) VISIBLE;

CREATE INDEX `invoice_item_fk2_idx` ON `storedb`.`invoice_item` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `invoice_item_fk3_idx` ON `storedb`.`invoice_item` (`item_id` ASC) VISIBLE;

CREATE INDEX `invoice_item_fk4_idx` ON `storedb`.`invoice_item` (`invoice_id` ASC) VISIBLE;

CREATE INDEX `invoice_item_fk5_idx` ON `storedb`.`invoice_item` (`inventory_id` ASC) VISIBLE;

CREATE INDEX `invoice_item_pk1` ON `storedb`.`invoice_item` (`invoice_id` ASC, `inventory_id` ASC, `item_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`organization_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`organization_structure` (
  `org_structure_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  `org_structure_parent_id` INT(10) UNSIGNED NOT NULL,
  `org_structure_child_id` INT(10) UNSIGNED NOT NULL,
  `org_structure_type` INT(10) UNSIGNED NOT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`org_structure_id`),
  CONSTRAINT `organization_structure_fk1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `storedb`.`organization` (`organization_id`),
  CONSTRAINT `organization_structure_fk2`
    FOREIGN KEY (`org_structure_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `organization_structure_fk3`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `organization_structure_fk4`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `organization_structure_fk5`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `organization_structure_fk1_idx` ON `storedb`.`organization_structure` (`organization_id` ASC) VISIBLE;

CREATE INDEX `organization_structure_fk2_idx` ON `storedb`.`organization_structure` (`org_structure_type` ASC) VISIBLE;

CREATE INDEX `organization_structure_fk3_idx` ON `storedb`.`organization_structure` (`created_by` ASC) VISIBLE;

CREATE INDEX `organization_structure_fk4_idx` ON `storedb`.`organization_structure` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `organization_structure_fk5_idx` ON `storedb`.`organization_structure` (`active_flag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`po_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`po_item` (
  `po_item_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchase_order_id` INT(10) UNSIGNED NOT NULL,
  `item_id` INT(10) UNSIGNED NOT NULL,
  `inventory_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`po_item_id`),
  CONSTRAINT `po_item_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `po_item_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `po_item_fk3`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `storedb`.`purchase_order` (`purchase_order_id`),
  CONSTRAINT `po_item_fk4`
    FOREIGN KEY (`item_id`)
    REFERENCES `storedb`.`item` (`item_id`),
  CONSTRAINT `po_item_fk5`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `storedb`.`inventory` (`inventory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `po_item_fk1_idx` ON `storedb`.`po_item` (`created_by` ASC) VISIBLE;

CREATE INDEX `po_item_fk2_idx` ON `storedb`.`po_item` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `po_item_fk3_idx` ON `storedb`.`po_item` (`purchase_order_id` ASC) VISIBLE;

CREATE INDEX `po_item_fk4_idx` ON `storedb`.`po_item` (`item_id` ASC) VISIBLE;

CREATE INDEX `po_item_fk5_idx` ON `storedb`.`po_item` (`inventory_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`price` (
  `price_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `price_type` INT(10) UNSIGNED NOT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `price_amount` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`price_id`),
  CONSTRAINT `price_id_fk1`
    FOREIGN KEY (`item_id`)
    REFERENCES `storedb`.`item` (`item_id`),
  CONSTRAINT `price_id_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `price_id_fk3`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `price_id_fk4`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `price_fk5`
    FOREIGN KEY (`price_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `price_id_fk1_idx` ON `storedb`.`price` (`item_id` ASC) VISIBLE;

CREATE INDEX `price_id_fk2_idx` ON `storedb`.`price` (`created_by` ASC) VISIBLE;

CREATE INDEX `price_id_fk3_idx` ON `storedb`.`price` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `price_id_fk4_idx` ON `storedb`.`price` (`active_flag` ASC) VISIBLE;

CREATE INDEX `price_fk5_idx` ON `storedb`.`price` (`price_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`rental_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`rental_item` (
  `rental_item_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rental_id` INT(10) UNSIGNED NOT NULL,
  `item_id` INT(10) UNSIGNED NOT NULL,
  `inventory_id` INT(10) UNSIGNED NOT NULL,
  `rental_item_type` INT(10) UNSIGNED NULL,
  `rental_item_price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `rental_type` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`rental_item_id`),
  CONSTRAINT `rental_item_fk1`
    FOREIGN KEY (`rental_id`)
    REFERENCES `storedb`.`rental` (`rental_id`),
  CONSTRAINT `rental_item_fk2`
    FOREIGN KEY (`item_id`)
    REFERENCES `storedb`.`item` (`item_id`),
  CONSTRAINT `rental_item_fk3`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `rental_item_fk4`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `rental_item_fk5`
    FOREIGN KEY (`rental_item_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `rental_item_fk6`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `storedb`.`inventory` (`inventory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `natural_key` ON `storedb`.`rental_item` (`rental_item_id` ASC, `rental_id` ASC, `item_id` ASC, `rental_item_type` ASC, `rental_item_price` ASC) VISIBLE;

CREATE INDEX `rental_item_fk1_idx` ON `storedb`.`rental_item` (`rental_id` ASC) VISIBLE;

CREATE INDEX `rental_item_fk2_idx` ON `storedb`.`rental_item` (`item_id` ASC) VISIBLE;

CREATE INDEX `rental_item_fk3_idx` ON `storedb`.`rental_item` (`created_by` ASC) VISIBLE;

CREATE INDEX `rental_item_fk4_idx` ON `storedb`.`rental_item` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `rental_item_fk5_idx` ON `storedb`.`rental_item` (`rental_item_type` ASC) VISIBLE;

CREATE INDEX `rental_item_fk6_idx` ON `storedb`.`rental_item` (`inventory_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`salary` (
  `salary_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `salary_type` INT(10) UNSIGNED NOT NULL,
  `payday_type` INT(10) UNSIGNED NOT NULL,
  `pay_type` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `salary_amount` DECIMAL(10,2) NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`salary_id`),
  CONSTRAINT `salary_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `salary_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `salary_fk3`
    FOREIGN KEY (`salary_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `salary_fk4`
    FOREIGN KEY (`payday_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `salary_fk5`
    FOREIGN KEY (`contact_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `salary_fk6`
    FOREIGN KEY (`pay_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `salary_fk1_idx` ON `storedb`.`salary` (`created_by` ASC) VISIBLE;

CREATE INDEX `salary_fk2_idx` ON `storedb`.`salary` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `salary_fk3_idx` ON `storedb`.`salary` (`salary_type` ASC) VISIBLE;

CREATE INDEX `salary_fk4_idx` ON `storedb`.`salary` (`payday_type` ASC) VISIBLE;

CREATE INDEX `salary_fk5_idx` ON `storedb`.`salary` (`contact_id` ASC) VISIBLE;

CREATE INDEX `salary_fk6_idx` ON `storedb`.`salary` (`pay_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`street_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`street_address` (
  `street_address_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address_id` INT(10) UNSIGNED NOT NULL,
  `street_address_name` CHAR(60) NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`street_address_id`),
  CONSTRAINT `street_address_fk1`
    FOREIGN KEY (`address_id`)
    REFERENCES `storedb`.`address` (`address_id`),
  CONSTRAINT `street_address_fk2`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `street_address_fk3`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `street_address_fk1_idx` ON `storedb`.`street_address` (`address_id` ASC) VISIBLE;

CREATE INDEX `street_address_fk2_idx` ON `storedb`.`street_address` (`created_by` ASC) VISIBLE;

CREATE INDEX `street_address_fk3_idx` ON `storedb`.`street_address` (`last_updated_by` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`telephone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`telephone` (
  `telephone_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `address_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `telephone_type` INT(10) UNSIGNED NOT NULL,
  `country_code` CHAR(3) NOT NULL,
  `area_code` CHAR(6) NOT NULL,
  `telephone_number` CHAR(10) NOT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `start_active_date` DATE NOT NULL,
  `end_active_date` DATE NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`telephone_id`),
  CONSTRAINT `telephone_fk2`
    FOREIGN KEY (`address_id`)
    REFERENCES `storedb`.`address` (`address_id`),
  CONSTRAINT `telephone_fk3`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `telephone_fk4`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `telephone_fk5`
    FOREIGN KEY (`organization_id`)
    REFERENCES `storedb`.`organization` (`organization_id`),
  CONSTRAINT `telephone_fk6`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `telephone_fk7`
    FOREIGN KEY (`telephone_type`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`),
  CONSTRAINT `telephone_fk8`
    FOREIGN KEY (`contact_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `telephone_fk2_idx` ON `storedb`.`telephone` (`address_id` ASC) VISIBLE;

CREATE INDEX `telephone_fk3_idx` ON `storedb`.`telephone` (`created_by` ASC) VISIBLE;

CREATE INDEX `telephone_fk4_idx` ON `storedb`.`telephone` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `telephone_fk5_idx` ON `storedb`.`telephone` (`organization_id` ASC) VISIBLE;

CREATE INDEX `telephone_fk6_idx` ON `storedb`.`telephone` (`active_flag` ASC) VISIBLE;

CREATE INDEX `telephone_fk7_idx` ON `storedb`.`telephone` (`telephone_type` ASC) VISIBLE;

CREATE INDEX `telephone_fk8_idx` ON `storedb`.`telephone` (`contact_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`genre_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`genre_source` (
  `genre_id` INT(10) UNSIGNED AUTO_INCREMENT,
  `contact_id` INT(10) UNSIGNED,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`genre_id`, `contact_id`),
  CONSTRAINT `genre_source_fk1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `storedb`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genre_source_fk2`
    FOREIGN KEY (`contact_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `genre_source_uq1` ON `storedb`.`genre_source` (`genre_id` ASC, `contact_id` ASC) VISIBLE;

CREATE INDEX `genre_source_fk1_idx` ON `storedb`.`genre_source` (`genre_id` ASC) VISIBLE;

CREATE INDEX `genre_source_fk2_idx` ON `storedb`.`genre_source` (`contact_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `storedb`.`employment_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`employment_history` (
  `employment_history_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `employment_start_date` DATE NOT NULL,
  `employment_end_date` DATE NULL DEFAULT NULL,
  `active_flag` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_updated_by` INT(10) UNSIGNED NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`employment_history_id`),
  CONSTRAINT `employment_history_fk1`
    FOREIGN KEY (`created_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `employment_history_fk2`
    FOREIGN KEY (`last_updated_by`)
    REFERENCES `storedb`.`system_user` (`system_user_id`),
  CONSTRAINT `employment_history_fk3`
    FOREIGN KEY (`employee_id`)
    REFERENCES `storedb`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employment_history_fk4`
    FOREIGN KEY (`active_flag`)
    REFERENCES `storedb`.`common_lookup` (`common_lookup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `employment_history_fk1_idx` ON `storedb`.`employment_history` (`created_by` ASC) VISIBLE;

CREATE INDEX `employment_history_fk2_idx` ON `storedb`.`employment_history` (`last_updated_by` ASC) VISIBLE;

CREATE INDEX `employment_history_fk3_idx` ON `storedb`.`employment_history` (`employee_id` ASC) VISIBLE;

CREATE INDEX `employment_history_fk4_idx` ON `storedb`.`employment_history` (`active_flag` ASC) VISIBLE;

USE `storedb` ;

-- -----------------------------------------------------
-- Placeholder table for view `storedb`.`current_rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`current_rental` (`account_number` INT, `full_name` INT, `TITLE` INT, `SUBTITLE` INT, `PRODUCT` INT, `check_out_date` INT, `expected_return_date` INT, `actual_return_date` INT);

-- -----------------------------------------------------
-- View `storedb`.`current_rental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storedb`.`current_rental`;
USE `storedb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`student`@`localhost` SQL SECURITY DEFINER VIEW `current_rental` AS select `m`.`account_number` AS `account_number`,(case when (`c`.`middle_name` is not null) then (`c`.`first_name` or ' ' or `c`.`middle_name` or ' ' or `c`.`last_name`) else (`c`.`first_name` or ' ' or `c`.`last_name`) end) AS `full_name`,`i`.`item_title` AS `TITLE`,`i`.`item_subtitle` AS `SUBTITLE`,substr(`cl`.`common_lookup_meaning`,1,3) AS `PRODUCT`,`r`.`check_out_date` AS `check_out_date`,`r`.`expected_return_date` AS `expected_return_date`,`r`.`actual_return_date` AS `actual_return_date` from (((((`common_lookup` `cl` join `contact` `c`) join `item` `i`) join `member` `m`) join `rental` `r`) join `rental_item` `ri`) where ((`r`.`contact_id` = `c`.`contact_id`) and (`r`.`rental_id` = `ri`.`rental_id`) and (`ri`.`item_id` = `i`.`item_id`) and (`i`.`item_type` = `cl`.`common_lookup_id`) and (`c`.`member_id` = `m`.`member_id`)) order by 1,2,3;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
